### PR TITLE
Optimized InnerJoin by indexing the dataframe key with a map.

### PR DESCRIPTION
**Pull request by claudiofahey**
InnerJoin of 100,000 rows with 100,000 rows went from 15 minutes to about 1 second. Similar optimizations can be done with Left and Right join.

### CODE REVIEW

**Comment by wolfeidau** [comment]
Are you planning to update this PR @claudiofahey ? 

I would love to continue this work optimising this library.

**Comment by kniren** [comment]
Hey @wolfeidau I think it's safe for you to pick this task up, since he had not answered to this issue at all so far. Thank you for your interest in the project, can't wait to see your PR!

**Comment by danicat** [comment]
Since this has been inactive for quite a long time I'm closing this down. If anyone is willing to continue this work please open a new PR targeting the `dev` branch.

**Comment by imthaghost** [comment]
Did this optimization ever make it out of testing?

**Comment by chrmang** [comment]
Hi @imthaghost ,

this PR is still not merged - it was closed due to inactivity. 

I didn't see any benchmark results comparing the modifications to current code.

**Pull request closed without merging**
