### PR TITLE
feature: groupby and Aggregation

### PR DESCRIPTION
**Pull request by wanglong001**
I am a fan of Gota, I hope Gota will become better

ADD Feature：

1. Groupby
2. Aggregation

```go
groups := df.GroupBy("key1", "key2") // Group by column "key1", and column "key2" 
aggre := groups.Aggregation([]AggregationType{Aggregation_MAX, Aggregation_MIN}, []string{"values", "values2"}) // Maximum value in column "values",  Minimum value in column "values2"
```

image

image

### CODE REVIEW

**Comment by wanglong001** [comment]
same issue: https://github.com/go-gota/gota/issues/33

**Review by kmrx — COMMENTED** [review]
Might need to modify the Series to include SUM and COUNT. That can enable the aggregation to include both. I can take a stab at it. @kniren, @wanglong001 thoughts? Thanks

**Comment by wanglong001** [comment]
@kmrx  @kniren 

Series has SUM and COUNT functions better

**Comment by VulgarnyKarlson** [comment]
+1

**Comment by chrmang** [comment]
@wanglong001 : can you change the change the target branch to `dev`, please?

**Comment by wanglong001** [comment]
@chrmang I resolved the conflict

**Pull request merged**
