### PR TITLE
use go mod and fix github.com paths and add float32

### PR DESCRIPTION
**Pull request by pa-m**
Hi,
module was unusable since github path changed but source had references to previous github url.
Best regards

### CODE REVIEW

**Comment by zeroviscosity** [comment]
I think this should be two PRs: one for the go mod update and a separate one for the float32 changes.

**Comment by pa-m** [comment]
> I think this should be two PRs: one for the go mod update and a separate one for the float32 changes.

Right, but 2nd depends from 1st

**Comment by danicat** [comment]
@pa-m please target your PR to the `dev` branch instead of master.

**Comment by kniren** [comment]
Already fixed in #97

**Pull request closed without merging**
