### PR TITLE
Add go.mod and go.sum

### PR DESCRIPTION
**Pull request by typeless**
Add support for Go modules.
It enables me to do local development (along with my application which uses gota) with the 'replace' directive.

### CODE REVIEW

**Comment by kniren** [comment]
I need to delve a bit deeper into go modules before reviewing this PR.

**Comment by chrstphlbr** [comment]
The dev branch already offers support for Go modules; so once dev gets merged into master, this PR should resolve itself

**Comment by chrstphlbr** [comment]
Actually my PR #97 addressed exactly the same and was merged a while ago

**Comment by kniren** [comment]
Yikes, sorry @chrstphlbr seems like I screw something up when I was preparing the last release, because the modules are clearly not included in dev right now :(

**Pull request closed without merging**
