### PR TITLE
Implement MapFunc method to support function application over Series Elements

### PR DESCRIPTION
**Pull request by szaydel**
I am not sure if you find this in any way interesting. I am still planning to PR other bits, like the Histogram, but wanted to give it a bit more time and thought. I found having a mapping method that does not affect length of series useful, and while perhaps this is not the best implementation, if you think you have interest, I am sure given feedback we can make it better.

Thanks for considering this changeset. Cheers.

### CODE REVIEW

**Comment by szaydel** [comment]
I think this sounds quite reasonable really. I feel like it is limiting in some ways to do this, but it does reduce the size of that worm can you mentioned. Let me give this a bit more thought and perhaps I will have a better alternative, otherwise given your suggestion will you consider merging it in, or do you feel value is not there, or not in line with what you see for this package? Thanks!

**Comment by szaydel** [comment]
I think you are right about this one. I am going to go ahead make changes and make sure it feels OK, and add some tests.

**Comment by szaydel** [comment]
I created a new PR with another version of this based on your suggestions. Perhaps we can just resolve this issue since I used a different branch and target `dev` this time instead of `master`?

Thanks!

**Comment by danicat** [comment]
@szaydel since you've already proposed a different solution in #57 I'm closing this one.

**Pull request closed without merging**
